### ISSUE TITLE
Themes do not work after Storybook upgrade from 6.1.16 to 6.1.17 

### ISSUE THREAD

**Issue by jokerosky** [mayteio/storybook-addon-materialui#7]
My preview.tsx  file:

```
export const decorators = [
  withI18next({
    i18n,
    languages: {
      en: 'English',
      ar: 'Arabic',
    },
  }),
  withMuiTheme(themes),
  Story => (
    <Suspense fallback={<CustomBackdrop open />}>
      <Story />
    </Suspense>
  ),
];
```

Themes appear in dropdown of Material UI tab, but not been changed and applied, looks like there is a problem with 
https://github.com/mayteio/storybook-addon-materialui/blob/master/src/Wrapper.tsx#L41

**Comment by jokerosky** [comment]
I've found the problem. Need to delete yarn.lock and package-lock.json and reinstall all packages. Because there were different versions of @material-ui/styles for the addon and the project.

**Comment by mayteio** [comment]
Thanks Tony. Can you submit a PR if necessary?
